// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ecfrInsights.Data;

#nullable disable

namespace ecfrInsights.Data.Migrations
{
    [DbContext(typeof(EcfrContext))]
    [Migration("20260116061151_TitleComplexities")]
    partial class TitleComplexities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ecfrInsights.Data.Entities.GraphsModel", b =>
                {
                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentSlug")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SortableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Slug");

                    b.HasIndex("ParentSlug");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.AgencyHierarchy", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CfrReferenceNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.HasKey("Slug", "CfrReferenceNumber");

                    b.HasIndex("CfrReferenceNumber");

                    b.ToTable("AgencyHierarchies");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.AgencyStatistics", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ForDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ComplexityScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCfrReferences")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSubAgencies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalWords")
                        .HasColumnType("INTEGER");

                    b.HasKey("Slug", "ForDate");

                    b.ToTable("AgencyStatistics");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.CfrHierarchy", b =>
                {
                    b.Property<string>("CfrReferenceNumber")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgencySlug")
                        .HasColumnType("TEXT");

                    b.Property<string>("Appendix")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Authority")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CfrReferenceTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Chapter")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Citation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestAmendedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LatestIssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParentCfrReferenceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Part")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ReferenceContent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Reserved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subchapter")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Subpart")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<int>("TitleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpToDateAsOf")
                        .HasColumnType("datetime2");

                    b.HasKey("CfrReferenceNumber");

                    b.HasIndex("AgencySlug");

                    b.HasIndex("ParentCfrReferenceNumber");

                    b.HasIndex("TitleNumber");

                    b.ToTable("CfrHierarchies");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.CfrHierarchyHistory", b =>
                {
                    b.Property<string>("CfrReferenceNumber")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Appendix")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Authority")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CfrReferenceTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Chapter")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Citation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestAmendedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LatestIssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParentCfrReferenceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Part")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ReferenceContent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Reserved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subchapter")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Subpart")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<int>("TitleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpToDateAsOf")
                        .HasColumnType("datetime2");

                    b.HasKey("CfrReferenceNumber");

                    b.HasIndex("ParentCfrReferenceNumber");

                    b.HasIndex("TitleNumber");

                    b.ToTable("CfrHierarchyHistories");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.CfrTitle", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LatestAmendedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LatestIssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Reserved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpToDateAsOf")
                        .HasColumnType("datetime2");

                    b.Property<string>("XmlDocumentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Number");

                    b.ToTable("CfrTitles");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.CfrTitleComplexity", b =>
                {
                    b.Property<int>("Title")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ComplexityScore")
                        .HasPrecision(18, 4)
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DateComputed")
                        .HasColumnType("TEXT");

                    b.Property<int>("HierarchicalCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("NormAgencies")
                        .HasPrecision(18, 4)
                        .HasColumnType("REAL");

                    b.Property<double>("NormCorrections")
                        .HasPrecision(18, 4)
                        .HasColumnType("REAL");

                    b.Property<double>("NormHierarchical")
                        .HasPrecision(18, 4)
                        .HasColumnType("REAL");

                    b.Property<double>("NormWordcount")
                        .HasPrecision(18, 4)
                        .HasColumnType("REAL");

                    b.Property<int>("TotalAgencies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCorrections")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wordcount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Title");

                    b.ToTable("CfrTitleComplexities");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.CfrTitleHistory", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LatestAmendedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LatestIssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Reserved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpToDateAsOf")
                        .HasColumnType("datetime2");

                    b.Property<string>("XmlDocumentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Number");

                    b.ToTable("CfrTitleHistories");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.Correction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectiveAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisplayInToc")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ErrorCorrected")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ErrorOccurred")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrCitation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Title")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.HasIndex("Year");

                    b.ToTable("Corrections");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.SyncStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncStatuses");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.GraphsModel", b =>
                {
                    b.HasOne("ecfrInsights.Data.Entities.GraphsModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentSlug")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.AgencyHierarchy", b =>
                {
                    b.HasOne("ecfrInsights.Data.Entities.CfrHierarchy", "CfrHierarchy")
                        .WithMany("AgencyHierarchies")
                        .HasForeignKey("CfrReferenceNumber")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("ecfrInsights.Data.Entities.GraphsModel", "GraphsModel")
                        .WithMany("AgencyHierarchies")
                        .HasForeignKey("Slug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GraphsModel");

                    b.Navigation("CfrHierarchy");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.AgencyStatistics", b =>
                {
                    b.HasOne("ecfrInsights.Data.Entities.GraphsModel", "GraphsModel")
                        .WithMany("Statistics")
                        .HasForeignKey("Slug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GraphsModel");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.CfrHierarchy", b =>
                {
                    b.HasOne("ecfrInsights.Data.Entities.CfrHierarchy", "ParentReference")
                        .WithMany("ChildReferences")
                        .HasForeignKey("ParentCfrReferenceNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecfrInsights.Data.Entities.CfrTitle", "Title")
                        .WithMany("CfrReferences")
                        .HasForeignKey("TitleNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentReference");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.CfrHierarchyHistory", b =>
                {
                    b.HasOne("ecfrInsights.Data.Entities.CfrHierarchy", "CurrentHierarchy")
                        .WithMany("Histories")
                        .HasForeignKey("CfrReferenceNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecfrInsights.Data.Entities.CfrHierarchyHistory", "ParentReference")
                        .WithMany("ChildReferences")
                        .HasForeignKey("ParentCfrReferenceNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecfrInsights.Data.Entities.CfrTitleHistory", "Title")
                        .WithMany("CfrHierarchyHistories")
                        .HasForeignKey("TitleNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentHierarchy");

                    b.Navigation("ParentReference");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.Correction", b =>
                {
                    b.HasOne("ecfrInsights.Data.Entities.CfrTitle", "CfrDocument")
                        .WithMany("Corrections")
                        .HasForeignKey("Title")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CfrDocument");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.GraphsModel", b =>
                {
                    b.Navigation("AgencyHierarchies");

                    b.Navigation("Children");

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.CfrHierarchy", b =>
                {
                    b.Navigation("AgencyHierarchies");

                    b.Navigation("ChildReferences");

                    b.Navigation("Histories");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.CfrHierarchyHistory", b =>
                {
                    b.Navigation("ChildReferences");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.CfrTitle", b =>
                {
                    b.Navigation("CfrReferences");

                    b.Navigation("Corrections");
                });

            modelBuilder.Entity("ecfrInsights.Data.Entities.CfrTitleHistory", b =>
                {
                    b.Navigation("CfrHierarchyHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
